#--- BASIC IMPORTS ---#
import os
import logging

#--- IMPORTS ---#
import numpy as np
from collections import Counter
import matplotlib.pyplot as plt
import seaborn as sns
import cv2
import pandas as pd
import geopandas as gpd
from pyproj import CRS
import plotly.graph_objects as go
from PIL import Image
import io
from shapely.geometry import box 
import math

#--- LIBRARIES ---#
from libs.file_handler import FileHandler
from libs.image_processor import ImageProcessor
from libs.spatial_metadata import SpatialMetadataService
from libs.annotation_generator import AnnotationGenerator
from libs.visualiser import Visualiser
from libs.write_report import ReportArtefactManager, WriteReport
from libs.eda.plotting import EDAPlotter
from libs.eda.sections import EDASections
from libs.eda.indices import EDAIndexAnalysis
from models.context import EDAContext
from models.reportsection import ReportSection
from models.metadata import SpatialMetadata

#--- LOGGING CONFIG ---#
cv2.utils.logging.setLogLevel(cv2.utils.logging.LOG_LEVEL_SILENT)
logging.getLogger("kaleido").setLevel(logging.ERROR)
logging.getLogger("plotly").setLevel(logging.ERROR)

#--- DATASET EDA ---#
'''
This class is used to perform exploratory data analysis on a dataset.
It is initialised with a directory containing images and masks.
Consists of methods for:
    - loading images and masks
    - analysis 
    - visualisation of analysis results

A full EDA report is generated by running the report() method.
'''

class DatasetEDA:
    def __init__(self, data_dir, class_id, set_name, config=None, stage='pre', spatial_metadata=None):
        '''
        DatasetEDA is initialised with a directory containing images and masks. It uses FileHandler to load and filter the dataset.
        Args:
            data_dir (str): Path to the directory containing the dataset (images, masks, etc.)
            class_id (int): Class ID for mask filtering.
            set_name (str): Set name for mask filtering.
            config (dict): Configuration dictionary for FileHandler and processing.
            stage (str): 'pre' for pre-processing, 'post' for post-processing. Used for labeling/reporting and for spatial metadata loading. Default is 'pre'.
            spatial_metadata (SpatialMetadata): [Optional] ]Spatial metadata object for user input, if the dataset has no actual spatial metadata.
            sample_size (int): Number of images/masks to sample for EDA, particularly for methods that are more compute intensive.
        '''
        self.config = config or {}
        self.data_dir = data_dir
        self.class_id = class_id
        self.set_name = set_name
        self.file_handler = FileHandler(self.config)
        self.image_processor = ImageProcessor(self.config)
        self.spatial_metadata_service = SpatialMetadataService(self.config)
        self.annotation_generator = AnnotationGenerator(self.config)
        self.visualiser = Visualiser(self.config)
        self.plotter = EDAPlotter(config=self.config, top_k=self.top_k if hasattr(self, "top_k") else 10, set_name=set_name, logger=logging.getLogger(__name__))
        self.sections_builder = EDASections(self)
        self.image_paths, self.mask_paths = self.file_handler.load_dataset(data_dir)       
        self.sample_size = min(self.config.get('sample_size', 50), len(self.image_paths), len(self.mask_paths)) 
        self.top_k = self.config.get('top_k', 10)
        self.plotter.top_k = self.top_k
        self.stage = stage

        if self.stage == 'post':
            self.spatial_metadata_csv_path = os.path.join(data_dir, 'dataset_file_directory.csv')

        if spatial_metadata is not None:
            self.spatial_mode = 'dataset_level'
            self.spatial_metadata = spatial_metadata
        else:
            self.spatial_mode = 'per_image'

        # fix sample indices for methods that require sampling
        np.random.seed(self.config.get('random_seed', 42))  

        self.sample_indices = np.random.choice(len(self.image_paths), self.sample_size, replace=False)

        self.image_shapes_counts = None
        self.mask_shapes_counts = None
        
        self.only_one_shape = True 
        self.only_one_class = True 
        self.image_mask_size_match = False 
        self.classes = class_id #assumes single class as default --> will be overwritten by unique_mask_values method if it is multiclass

        self.logger = logging.getLogger(__name__)
        self.logger.setLevel(logging.ERROR)
        self.index_analysis = EDAIndexAnalysis(config=self.config, logger=self.logger)

    def load_image(self, i):
        if i >= len(self.image_paths):
            self.logger.error(f"Image index out of range: {i} is greater than the number of images in the dataset: {len(self.image_paths)}")
            return None
        return self.image_processor.load_image(self.image_paths[i])
    
    def load_spatial_metadata(self, i):
        if i >= len(self.image_paths):
            self.logger.error(f"Image index out of range: {i} is greater than the number of images in the dataset: {len(self.image_paths)}")
            return None
        return self.spatial_metadata_service.get_spatial_metadata(self.image_paths[i])


    def load_mask(self, i):
        if i >= len(self.mask_paths):
            self.logger.error(f"Mask index out of range: {i} is greater than the number of masks in the dataset: {len(self.mask_paths)}")
            return None
        return self.image_processor.load_mask(self.mask_paths[i])
    
    def valid_image(self, image):
        return image.ndim == 3 and image.shape[2] == 3
    
    def ensure_shapes_loaded(self):
        '''
        Iterate through all images and masks to:
        - get all existing shapes in dataset
        - set only_one_shape and ref_shape
        - set image_mask_size_match to True if all shapes are the same; False if shapes are not the same
        - set ref_shape to the max height and width of the shapes if more than one shape is found; (0, 0) if no shapes are found
        - set image_shapes_counts and mask_shapes_counts to the counts of the shapes; {(0,0): 1} if no shapes are found
        '''
        if self.image_shapes_counts is not None:
            self.logger.info("Shapes already loaded. Returning.")
            return
        image_shapes = []
        mask_shapes = []

        if len(self.image_paths) == 0:
            self.logger.warning("No image files detected. Unable to compute metrics. Setting reference shape to (0, 0) and image shapes count to {(0,0): 1}.")
            self.ref_shape = (0, 0)
            self.image_shapes_counts = {(0,0): 1}
            return
        if len(self.mask_paths) == 0:
            self.logger.warning("No mask files detected. Unable to compute metrics. Setting reference shape to (0, 0) and mask shapes count to {(0,0): 1}.")
            self.ref_shape = (0, 0)
            self.mask_shapes_counts = {(0,0): 1}
            return

        for i in range(len(self.image_paths)):
            try:
                img = self.load_image(i)
                mask = self.load_mask(i)
                image_shapes.append(img.shape if img is not None else (0,0))
                mask_shapes.append(mask.shape if mask is not None else (0,0))

                del img
                del mask

            except Exception as e:
                self.logger.warning(f"Failed to load pair {i}: {self.image_paths[i]}, {self.mask_paths[i]}. Error: {e}")
                image_shapes.append((0,0))
                mask_shapes.append((0,0))

        self.image_shapes_counts = dict(Counter(image_shapes))
        self.mask_shapes_counts = dict(Counter(mask_shapes))

        if (len(self.image_shapes_counts) == 1 and next(iter(self.image_shapes_counts.keys())) == (0,0)):
            self.ref_shape = (0, 0)
            self.logger.warning("No image shapes detected. Unable to compute metrics. Returning empty dictionary and setting reference shape to (0, 0).")
            return {}
        if len(self.mask_shapes_counts) == 0:
            self.ref_shape = (0, 0)
            self.logger.warning("No mask shapes detected. Unable to compute metrics. Returning empty dictionary and setting reference shape to (0, 0).")
            return {}

        if len(self.image_shapes_counts) == 1 and len(self.mask_shapes_counts) == 1:
            self.ref_shape = next(iter(self.image_shapes_counts.keys()))[:2]
            self.logger.info(f"All images and masks have the same shape. Reference shape set to: {self.ref_shape}")
        else:
            self.only_one_shape = False
            all_shapes = [shape for shape in self.image_shapes_counts.keys() if shape is not None]
            if list(self.image_shapes_counts.keys()) == list(self.mask_shapes_counts.keys()): # since images and masks are loaded in pairs, we shouldn't need to sort the lists. if they don't match it means the image/mask pairs don't match, even if the overall lists of shapes are the same.
                self.image_mask_size_match = True
            else:
                self.image_mask_size_match = False #although it is false by default, declare explicitly for safety
                self.logger.warning(f"Image and mask shapes are not uniform. Image shape set: {self.image_shapes_counts.keys()}. Mask shape set: {self.mask_shapes_counts.keys()}")
                all_shapes.extend([shape for shape in self.mask_shapes_counts.keys() if shape is not None])
            max_height = max(shape[0] for shape in all_shapes)
            max_width = max(shape[1] for shape in all_shapes)
            self.ref_shape = (max_height, max_width)
            self.logger.info(f"Images and masks have more than one shape. Total number of image shapes is {len(self.image_shapes_counts)}. Total number of mask shapes is {len(self.mask_shapes_counts)}. Reference shape set to: {self.ref_shape}")


    # --- General Analysis Methods --- #
    def compute_basic_metrics(self):
        '''
        Computes and returns basic dataset metrics such as:
        - number of image and mask files/tiles
        - size of image and mask files/tiles
        - basic statistics for image height and width (mean, min, max)
        
        Returns: dict of nums and dicts
        '''
        self.ensure_shapes_loaded()

        metrics = {}

        metrics['image_count']= len(self.image_paths)
        metrics['mask_count'] = len(self.mask_paths)

        metrics['image_shapes'] = self.image_shapes_counts
        metrics['mask_shapes'] = self.mask_shapes_counts

        weighted_h = weighted_w = total = 0
        heights = []
        widths = []

        for shape, count in self.image_shapes_counts.items():
            if shape is None:
                continue
            h, w = shape[0], shape[1]
            weighted_h += h * count
            weighted_w += w * count
            total += count
            heights.append(h)
            widths.append(w)
        if total > 0:
            metrics['mean_height'] = weighted_h / total
            metrics['mean_width'] = weighted_w / total
        else:
            metrics['mean_height'] = metrics['mean_width'] = np.nan

        metrics['min_height'] = np.min(heights) if heights else np.nan
        metrics['max_height'] = np.max(heights) if heights else np.nan
        metrics['min_width'] = np.min(widths) if widths else np.nan
        metrics['max_width'] = np.max(widths) if widths else np.nan
        
        weighted_mh = weighted_mw = total_m = 0
        mask_heights = []
        mask_widths = []

        for shape, count in self.mask_shapes_counts.items():
            if shape is None:
                continue
            h, w = shape[0], shape[1]
            weighted_mh += h * count
            weighted_mw += w * count
            total_m += count
            mask_heights.append(h)
            mask_widths.append(w)
        
        if total_m > 0:
            metrics['mean_mask_height'] = weighted_mh / total_m
            metrics['mean_mask_width'] = weighted_mw / total_m
        else:
            metrics['mean_mask_height'] = metrics['mean_mask_width'] = np.nan
        metrics['min_mask_height'] = np.min(mask_heights) if mask_heights else np.nan
        metrics['max_mask_height'] = np.max(mask_heights) if mask_heights else np.nan
        metrics['min_mask_width'] = np.min(mask_widths) if mask_widths else np.nan
        metrics['max_mask_width'] = np.max(mask_widths) if mask_widths else np.nan

        return metrics

    def _summarise_basic_metrics(self, metrics: dict) -> list[str]:
        '''
        Summarises the basic metrics for report text.
        '''
        image_count = metrics['image_count']
        top_img_counts = sorted(metrics['image_shapes'].items(), key=lambda kv: kv[1], reverse=True)[:5]
        mask_count = metrics['mask_count']
        top_mask_counts = sorted(metrics['mask_shapes'].items(), key=lambda kv: kv[1], reverse=True)[:5]

        lines = [
            "Summary of Basic Metrics:",
            f" - Number of images: {image_count}",
            f" - Number of masks: {mask_count}",
            "Top 5 image shapes:",
        ]

        lines.extend([f"- {shape[0]}x{shape[1]} ({count})" for shape, count in top_img_counts])
        lines.append("Top 5 mask shapes:")
        lines.extend([f"- {shape[0]}x{shape[1]} ({count})" for shape, count in top_mask_counts])
        lines += [
            "Image size statistics:",
            f"- Mean height: {metrics['mean_height']:.2f}",
            f"- Mean width: {metrics['mean_width']:.2f}",
            f"- Min height: {metrics['min_height']:.2f}",
            f"- Max height: {metrics['max_height']:.2f}",
            f"- Min width: {metrics['min_width']:.2f}",
            f"- Max width: {metrics['max_width']:.2f}",
            "Mask size statistics:",
            f"- Mean height: {metrics['mean_mask_height']:.2f}",
            f"- Mean width: {metrics['mean_mask_width']:.2f}",
            f"- Min height: {metrics['min_mask_height']:.2f}",
            f"- Max height: {metrics['max_mask_height']:.2f}",
            f"- Min width: {metrics['min_mask_width']:.2f}",
            f"- Max width: {metrics['max_mask_width']:.2f}",
        ]
        return lines


    #--- Spatial Analysis Methods --- #
    def compute_spatial_metadata(self):
        '''
        Computes and returns spatial metadata of the dataset.
        
        Returns: 
            list of SpatialMetadata objects.
        '''
        if self.spatial_mode == 'dataset_level':
            n = len(self.image_paths)
            base = self.spatial_metadata
            return [base for _ in range(n)]
        
        if self.stage == 'post':
            self.spatial_metadata = self.spatial_metadata_service.get_spatial_metadata_from_csv(self.spatial_metadata_csv_path)
            return self.spatial_metadata
        
        try:
            self.spatial_metadata = [self.load_spatial_metadata(i) for i in range(len(self.image_paths))]
            return self.spatial_metadata
        except Exception:
            self.logger.exception("Failed to compute spatial metadata.")
            return [None] * len(self.image_paths)

    def _summarise_spatial_metadata(
        self,
        spatial_metadata: list[SpatialMetadata],
        center_lat: float,
        center_lon: float,
        minx: float,
        miny: float,
        maxx: float,
        maxy: float,
        zoom_level: float,
        max_countries: int = 5,
        max_crs: int = 3,
    ) -> list[str]:

        valid = [sm for sm in spatial_metadata if sm is not None]
        n_total = len(spatial_metadata)
        n_valid = len(valid)
        with_bounds = [sm for sm in valid if sm.bounds is not None]
        with_centroid_wgs84 = [sm for sm in valid if sm.centroid_wgs84 is not None]
        
        crs_counts: dict[str, int] = {}
        for sm in valid:
            if sm.epsg is not None:
                key = f"EPSG:{sm.epsg}"
            elif sm.crs_wkt:
                try:
                    key = CRS.from_wkt(sm.crs_wkt).to_string()
                except Exception:
                    key = "WKT (unparsed)"
            else:
                continue
            crs_counts[key] = crs_counts.get(key, 0) + 1
        top_crs = sorted(crs_counts.items(), key=lambda kv: kv[1], reverse=True)[:max_crs]
        country_counts: dict[str, int] = {}
        for sm in valid:
            if sm.country:
                country_counts[sm.country] = country_counts.get(sm.country, 0) + 1
        top_countries = sorted(country_counts.items(), key=lambda kv: kv[1], reverse=True)[:max_countries]
        mean_cm_values = [sm.mean_cm_per_pixel for sm in valid if sm.mean_cm_per_pixel is not None]
        if mean_cm_values:
            mean_cm_values_sorted = sorted(mean_cm_values)
            n = len(mean_cm_values_sorted)
            median_cm = (
                mean_cm_values_sorted[n // 2]
                if n % 2 == 1
                else (mean_cm_values_sorted[n // 2 - 1] + mean_cm_values_sorted[n // 2]) / 2
            )
            cm_line = (
                f"Mean cm/pixel: min={min(mean_cm_values_sorted):.2f}, "
                f"med={median_cm:.2f}, max={max(mean_cm_values_sorted):.2f}"
            )
        else:
            cm_line = "Mean cm/pixel: unavailable"
        if top_crs:
            crs_line = "Top CRS: " + ", ".join([f"{crs} ({count})" for crs, count in top_crs])
        else:
            crs_line = "Top CRS: unavailable"
        if top_countries:
            country_line = "Top countries: " + ", ".join([f"{country} ({count})" for country, count in top_countries])
        else:
            country_line = "Top countries: unavailable"
        lines = [
            f"Records: {n_valid}/{n_total} valid",
            f"Bounds (WGS84): min({minx:.5f}, {miny:.5f}) max({maxx:.5f}, {maxy:.5f})",
            f"Map center (lat, lon): ({center_lat:.5f}, {center_lon:.5f}), zoom={zoom_level:.2f}",
            f"With bounds: {len(with_bounds)} | With centroid_wgs84: {len(with_centroid_wgs84)}",
            crs_line,
            cm_line,
            country_line,
        ]
        return lines
    
    def _summarise_spatial_metadata_no_map(self, spatial_metadata: list[SpatialMetadata]) -> list[str]:
        '''
        Summarises spatial metadata without a map.
        '''
        max_countries = self.config.get('top_k', 10)
        max_crs = self.config.get('top_k', 10)
        valid = [sm for sm in spatial_metadata if sm is not None]
        n_total = len(spatial_metadata)
        n_valid = len(valid)
        with_bounds = sum(1 for sm in valid if sm.bounds is not None)
        with_c = sum(1 for sm in valid if sm.centroid_wgs84 is not None)
        crs_counts: dict[str, int] = {}
        for sm in valid:
            if sm.epsg is not None:
                key = f"EPSG:{sm.epsg}"
            elif sm.crs_wkt:
                try:
                    key = CRS.from_wkt(sm.crs_wkt).to_string()
                except Exception:
                    key = "WKT (unparsed)"
            else:
                continue
            crs_counts[key] = crs_counts.get(key, 0) + 1
        top_crs = sorted(crs_counts.items(), key=lambda kv: kv[1], reverse=True)[:max_crs]
        country_counts: dict[str, int] = {}
        for sm in valid:
            if sm.country:
                country_counts[sm.country] = country_counts.get(sm.country, 0) + 1
        top_countries = sorted(country_counts.items(), key=lambda kv: kv[1], reverse=True)[:max_countries]
        crs_line = "Top CRS: " + ", ".join(f"{c} ({n})" for c, n in top_crs) if top_crs else "Top CRS: unavailable"
        country_line = (
            "Top countries: " + ", ".join(f"{c} ({n})" for c, n in top_countries)
            if top_countries
            else "Top countries: unavailable"
        )
        summary = [
            f"Records: {n_valid}/{n_total} valid (non-null metadata objects)",
            "Map extent: not available (insufficient CRS/bounds or map omitted).",
            f"With bounds: {with_bounds} | With centroid_wgs84: {with_c}",
            crs_line,
            country_line,
        ]
        return summary

    # --- Image Analysis Methods --- #
    def compute_colour_distribution(self):
        '''
        Computes unique colours, dominant colours, and colour distribution statistics for the dataset based on strided pixels.
        Pixel stride varies according to image size. Target pixels will be set to 512x512=262144 pixels.

        Note: Colour channels are in BGR order (OpenCV convention).
        
        By default, takes only a sample of the dataset which is fixed in the config.

        Args:
            top_k (int): number of top colours to store. Default is 10.
        
        Returns:
            dict: Contains unique colours, colour counts, dominant colour, average colour (BGR), and colour distribution percentages.
        '''
        if len(self.image_paths) == 0:
            self.logger.warning("No image files detected. Unable to compute colour distribution. Returning empty dictionary.")
            return {}

        colour_counter = Counter()
        sum_pixels = np.zeros(3)
        total_pixels = 0

        for i in self.sample_indices:
            image = self.load_image(i)

            if self.valid_image(image):
                stride = max(1, int(np.sqrt(image.shape[0] * image.shape[1] / 262144))) # see docstring above. target for stride of 1 is 512x512=262144 pixels.
                pixels = image[::stride, ::stride, :].reshape(-1, 3)

                colour_counter.update(map(tuple, pixels))

                sum_pixels += pixels.sum(axis=0)
                total_pixels += pixels.shape[0]

            else:
                self.logger.warning(f"Image {i} is not a 3-channel image. Skipping.")
                continue
        
        if total_pixels == 0 or not colour_counter:
            self.logger.warning("No valid 3-channel images for colour distribution.")
            return {}
        
        dominant_colour = max(colour_counter, key=colour_counter.get)           # note that in mixed-sized datasets with a big range of image sizes, this will be biased towards larger images, but it is meaningful to see the dominant colour in the overall dataset.
        average_colour = tuple((sum_pixels / total_pixels).astype(int))
        colour_distribution = {
            colour: (count / total_pixels * 100) 
            for colour, count in colour_counter.items()
            }

        colour_dict = {
            'unique_colours': colour_counter.most_common(self.top_k),
            'dominant_colour': dominant_colour,
            'average_colour_bgr': average_colour,
            'colour_distribution_percentages': colour_distribution,
            'total_unique_colours': len(colour_counter),
            'total_pixels_analysed': total_pixels
        }
        
        return colour_dict 

    @staticmethod
    def _hist_percentiles(counts, bin_edges, qs=(1, 25, 50, 75, 99)):
        cdf = np.cumsum(counts)
        if cdf[-1] == 0:
            return np.array([np.nan] * len(qs))
        targets = np.array(qs) / 100.0 * cdf[-1]
        idxs = np.searchsorted(cdf, targets, side="left")
        idxs = np.clip(idxs, 0, len(bin_edges) - 2)
        return bin_edges[idxs]

    def compute_intensity_histogram(self):
        '''
        Computes and returns colour/brightness distribution statistics for the dataset.
        Histogram data is a tuple (counts, bin_edges) as returned by np.histogram.
        Args:
            sample_size : int, number of images to sample. None by default (uses entire dataset. Use if dataset is too huge.
        Returns: 
            intensity_distribution:  dictionary of min/max/mean, histogram data, etc. for both overall and per colour channel values.
        '''
        if len(self.image_paths) == 0:
            self.logger.warning("No image files detected. Unable to compute intensity histogram. Returning empty dictionary.")
            return {}
        
        channel_dict = {"B": 0, "G": 1, "R": 2}
            
        intensity_distribution = {}
        bin_edges = np.linspace(0, 255, 51)

        all_channel_stats = {
            ch: {
                'sum': 0,
                'sum_sq': 0,
                'count': 0,
                'min': 255,
                'max': 0,
                'hist': np.zeros(50, dtype=np.float64)
            } for ch in channel_dict
        }
        grey_stats = {
            'sum': 0,
            'sum_sq': 0,
            'count': 0,
            'min': 255,
            'max': 0,
            'hist': np.zeros(50, dtype=np.float64)
        }

        for i in self.sample_indices:
            image = self.load_image(i)
            if not self.valid_image(image):
                self.logger.warning(f"Image {i} is not a valid image. Skipping.")
                continue
            pixels = image.reshape(-1, 3)
            b = pixels[:, 0]
            g = pixels[:, 1]
            r = pixels[:, 2]
            for channel, arr in (("B", b), ("G", g), ("R", r)):
                vals = arr.astype(np.float64, copy=False)
                all_channel_stats[channel]["sum"] += float(vals.sum())
                all_channel_stats[channel]["sum_sq"] += float(np.square(vals, dtype=np.float64).sum())
                all_channel_stats[channel]["count"] += vals.size
                all_channel_stats[channel]["min"] = min(all_channel_stats[channel]["min"], float(vals.min()))
                all_channel_stats[channel]["max"] = max(all_channel_stats[channel]["max"], float(vals.max()))
                all_channel_stats[channel]["hist"] += np.histogram(vals, bins=bin_edges)[0]
            
            grey = cv2.cvtColor(image.astype(np.float32, copy=False), cv2.COLOR_BGR2GRAY).ravel()
            grey_float = grey.astype(np.float64)
            grey_stats['sum'] += grey_float.sum()
            grey_stats['sum_sq'] += (grey_float**2).sum()
            grey_stats['count'] += grey_float.size
            grey_stats['min'] = min(grey_stats['min'], grey_float.min())
            grey_stats['max'] = max(grey_stats['max'], grey_float.max())
            grey_stats['hist'] += np.histogram(grey_float, bins=bin_edges)[0]
        
        if grey_stats['count'] == 0:
            self.logger.warning("No valid 3-channel images for intensity histogram.")
            return {}

        for channel in channel_dict:
            channel_data = all_channel_stats[channel]
            intensity_distribution[f'{channel}_mean_intensity'] = channel_data['sum'] / channel_data['count']
            intensity_distribution[f'{channel}_std_intensity'] = np.sqrt(channel_data['sum_sq'] / channel_data['count'] - intensity_distribution[f'{channel}_mean_intensity']**2)
            intensity_distribution[f'{channel}_min_intensity'] = channel_data['min']
            intensity_distribution[f'{channel}_max_intensity'] = channel_data['max']
            intensity_distribution[f'{channel}_percentiles'] = self._hist_percentiles(channel_data['hist'], bin_edges)
            intensity_distribution[f'{channel}_50_bins_intensity'] = (channel_data['hist'], bin_edges)
            
        intensity_distribution['mean_intensity'] = grey_stats['sum'] / grey_stats['count']
        intensity_distribution['std_intensity'] = np.sqrt(grey_stats['sum_sq'] / grey_stats['count'] - intensity_distribution['mean_intensity']**2)
        intensity_distribution['min_intensity'] = grey_stats['min']
        intensity_distribution['max_intensity'] = grey_stats['max']
        intensity_distribution['percentiles'] = self._hist_percentiles(grey_stats['hist'], bin_edges)
        intensity_distribution['50_bins_intensity'] = (grey_stats['hist'], bin_edges)

        return intensity_distribution


    
    def compute_indices(self, bins: int = 50, n_display: int = 5):
        '''
        Compute RGB-based vegetation/water proxy indices over sampled images.

        For each index:
        - accumulates a dataset-level histogram,
        - computes summary statistics from finite values,
        - stores up to n_display full index maps for randomly selected sample images.

        Args:
            bins (int): Number of histogram bins per index.
            n_display (int): Maximum number of sample index maps to keep per index.

        Returns:
            dict: {
                "histograms": dict[str, tuple[np.ndarray, np.ndarray]],
                    # index_name -> (counts, bin_edges)
                    # counts shape: (bins,), dtype int64
                    # bin_edges shape: (bins + 1,), dtype float32

                "summary": dict[str, dict[str, float | int | np.ndarray]],
                    # index_name -> {
                    #   "mean": float,
                    #   "std": float,
                    #   "min": float,
                    #   "max": float,
                    #   "count": int,
                    #   "percentiles": np.ndarray  # from _hist_percentiles(...), shape (5,)
                    # }

                "sample_maps": dict[str, list[np.ndarray]],
                    # index_name -> up to n_display 2D index arrays (one per selected image)
            }

        Notes:
            - Most indices use fixed histogram edges in [-1, 1].
            - EXG uses robust dynamic edges estimated from a pilot subset.
            - Only finite index values are included in histograms and summary statistics.
        '''

        index_names = ['rgbvi', 'vari', 'exg', 'gli', 'mgrvi', 'bri', 'bgi']
        
        if len(self.sample_indices) == 0:
            self.logger.warning("No sampled images available for index analysis.")
            return {'histograms': {}, 'summary': {}, 'sample_maps': {}, 'sample_ids': []}
        
        n_display = min(n_display, len(self.sample_indices))
        display_indices = set(np.random.choice(self.sample_indices, n_display, replace=False).tolist())
        
        bounded_names = {'rgbvi', 'vari', 'gli', 'mgrvi', 'bri', 'bgi'} # excluding exg for now because it is not naturally bounded to [-1, 1]
        exg_name = 'exg'
        bounded_edges = np.linspace(-1.0, 1.0, bins + 1, dtype=np.float32)

        exg_vals_for_range = []
        pilot_cap = min(len(self.sample_indices), max(25, int(0.2 * len(self.sample_indices))))
        for i in self.sample_indices[:pilot_cap]:
            image = self.load_image(i)
            if image is None or not self.valid_image(image):
                continue
            B, G, R = self.index_analysis._image_to_norm_BGR_float(image)
            exg_map = self.index_analysis.exg(B, G, R)
            vals = exg_map[np.isfinite(exg_map)]
            if vals.size:
                exg_vals_for_range.append(vals)
        if exg_vals_for_range:
            exg_concat = np.concatenate(exg_vals_for_range)
            lo, hi = np.percentile(exg_concat, [1, 99])
            if not np.isfinite(lo) or not np.isfinite(hi) or lo >= hi:
                lo, hi = -1.0, 1.0
        else:
            lo, hi = -1.0, 1.0
        exg_edges = np.linspace(lo, hi, bins + 1, dtype=np.float32)
        edges_by_name = {name: bounded_edges for name in bounded_names}
        edges_by_name[exg_name] = exg_edges
        histograms = {name: np.zeros(bins, dtype=np.int64) for name in index_names}
        summary_acc = {
            name: {"sum": 0.0, "sum_sq": 0.0, "count": 0, "min": np.inf, "max": -np.inf}
            for name in index_names
        }
        sample_maps = {name: [] for name in index_names}
        for i in self.sample_indices:
            image = self.load_image(i)
            if image is None or not self.valid_image(image):
                self.logger.warning(f"Image {i} is not a valid 3-channel image. Skipping.")
                continue
            B, G, R = self.index_analysis._image_to_norm_BGR_float(image)
            idx_maps = {
                "rgbvi": self.index_analysis.rgbvi(B, G, R),
                "vari": self.index_analysis.vari(B, G, R),
                "exg": self.index_analysis.exg(B, G, R),
                "gli": self.index_analysis.gli(B, G, R),
                "mgrvi": self.index_analysis.mgrvi(B, G, R),
                "bri": self.index_analysis.bri(B, G, R),
                "bgi": self.index_analysis.bgi(B, G, R),
            }
            for name, arr in idx_maps.items():
                vals = arr[np.isfinite(arr)]
                if vals.size == 0:
                    continue
                edges = edges_by_name[name]
                histograms[name] += np.histogram(vals, bins=edges)[0]
                acc = summary_acc[name]
                acc["sum"] += float(vals.sum())
                acc["sum_sq"] += float(np.square(vals, dtype=np.float64).sum())
                acc["count"] += int(vals.size)
                acc["min"] = min(acc["min"], float(vals.min()))
                acc["max"] = max(acc["max"], float(vals.max()))
                if i in display_indices and len(sample_maps[name]) < n_display:
                    sample_maps[name].append(arr)
        summary = {}
        for name, acc in summary_acc.items():
            if acc["count"] == 0:
                continue
            mean = acc["sum"] / acc["count"]
            var = max(0.0, acc["sum_sq"] / acc["count"] - mean**2)
            percentiles = self._hist_percentiles(histograms[name], edges_by_name[name])
            summary[name] = {
                "mean": mean,
                "std": float(np.sqrt(var)),
                "min": acc["min"],
                "max": acc["max"],
                "count": acc["count"],
                "percentiles": percentiles,
            }
        hist_out = {name: (histograms[name], edges_by_name[name]) for name in index_names}
        return {
            "histograms": hist_out,
            "summary": summary,
            "sample_maps": sample_maps
        }

    
    def compute_average_image(self):
        '''
        Computes the pixel-wise average image over the dataset (or a random sample).
        Average image that results will also be used to display the colour and intensity heatmaps,
        as well as to compute/display the contrast heatmap. 
        
        Reference shape is the max height and width of the shapes in the dataset.
        If the shapes are not the same, the images are padded to the reference shape.

        Returns: 
        avg_image : np.ndarray (average image) 
        '''
        if len(self.image_paths) == 0:
            self.logger.warning("No image files detected. Unable to compute average image. Returning None.")
            return None
        
        ref_shape = getattr(self, 'ref_shape', (0,0))
        if ref_shape == (0,0):
            self.logger.warning("No reference shape found. Unable to compute average image. Returning None.")
            return None

        image_stack = np.zeros((self.ref_shape[0], self.ref_shape[1], 3), dtype=np.float32)
        valid_count = 0

        for i in self.sample_indices:
            image = self.load_image(i)
            if self.valid_image(image):
                if self.only_one_shape:           
                    image_stack += image
                    valid_count += 1
                else:
                    img_size = image.shape[:2]
                    h_pad = self.ref_shape[0] - img_size[0]
                    w_pad = self.ref_shape[1] - img_size[1]
                    h_pad_top = h_pad//2
                    h_pad_bottom = h_pad - h_pad_top
                    w_pad_left = w_pad//2
                    w_pad_right = w_pad - w_pad_left
                    padding = ((h_pad_top, h_pad_bottom), (w_pad_left, w_pad_right), (0, 0)) # 0, 0 is for the channels
                    image = np.pad(image, padding, mode='constant', constant_values=0)
                    image_stack += image
                    valid_count += 1

            else:
                self.logger.warning(f"Image {i} is not a valid image. Skipping.")
                continue
    
        if valid_count == 0:
            self.logger.warning("No valid images found. Unable to compute average image. Returning None.")
            return None
        elif valid_count < len(self.sample_indices):
            self.logger.warning("Some images were invalid. Average image comprised of only these images.")

        avg_image = (image_stack / valid_count).astype(np.uint8)

        return avg_image

    def compute_contrast_heatmap(self, image, num_windows=25):
        '''
        Computes and returns a windowed grid of average local contrast values over the dataset.
        Each cell in the grid is the mean local contrast in that window.

        Args:
        image: np.ndarray from compute_average_image
        num_windows: int, number of windows to divide the image into. This is the number of rows and columns. Default is 25 for a total of 625 windows.
        Returns:
        contrast_map: np.ndarray of shape (num_windows, num_windows)

        NOTE: Rather than number of windows, we could use the window size to force square windows.
        NOTE: We can consider adding kernel as an argument so that different tasks can be achieved (e.g. edge detection)
        '''
        if not self.valid_image(image):
            self.logger.warning("Invalid image. Unable to compute contrast heatmap. Returning None.")
            return None
    
        grey = cv2.cvtColor(image.astype(np.float32, copy=False), cv2.COLOR_BGR2GRAY)
        h, w = grey.shape
        grid_h = h // num_windows
        grid_w = w // num_windows

        contrast_map = np.zeros((num_windows, num_windows))

        for i in range(num_windows):
            for j in range(num_windows):
                x1, y1 = j * grid_w, i * grid_h
                x2, y2 = (j + 1) * grid_w, (i + 1) * grid_h
                window = grey[y1:y2, x1:x2]

                if window.size > 0:
                    contrast_map[i, j] = window.std() 
                else:
                    contrast_map[i, j] = 0.0

        return contrast_map    


   # --- Object Analysis Methods --- #
    def get_mask_unique_values(self, mask):
        """
        Returns unique values for a single mask. Return value should be either a list of integers or colours. 
        Returns empty list if mask shape is unexpected.
        """
        if mask.ndim == 2:
            # Standard indexed mask
            return np.unique(mask).tolist()
        elif mask.ndim == 3 and mask.shape[2] == 3:
            pixels = mask.reshape(-1, 3)
            return list(map(tuple, np.unique(pixels, axis=0)))
        elif mask.ndim == 3 and mask.shape[0] == 1:
            mask = np.squeeze(mask)
            return np.unique(mask).tolist()
        else:
            self.logger.warning(f"Unexpected mask shape: {mask.shape}")
            return []

    def all_unique_mask_values(self):
        '''
        Finds all unique values in a sample of mask images and identifies whether it is a single or multiclass dataset.
        Returns:
        global_uniques: set of unique values
        '''
        global_uniques = set()
        for i in self.sample_indices:
            mask = self.load_mask(i)
            uniques = self.get_mask_unique_values(mask)
            if uniques is None:
                continue
            global_uniques.update(uniques)
        # Remove background for class count check
        foreground_uniques = [
            u for u in global_uniques
            if not (
                u == 0 or
                (isinstance(u, (tuple, list, np.ndarray)) and all(v == 0 for v in u))
            )
        ]
        if len(foreground_uniques) == 1:
            self.only_one_class = True
            self.logger.info("This is a single class dataset")
        else:
            self.only_one_class = False
            self.logger.info("This is a multiclass dataset.")
        self.classes = sorted(global_uniques, key=lambda x: (x if isinstance(x, int) else x[0]))
        return global_uniques


    def _compute_single_mask_stats(self, mask, polygons):
        '''
        Computes statistics for a single mask.
        '''
        if mask is None:
            return None
        h, w = mask.shape[:2]
        image_area = h * w
        cx_img, cy_img = (w / 2, h / 2)
        max_dist = np.sqrt(cx_img**2 + cy_img**2)

        polygon_areas = []
        polygon_centroids = []
        centre_bias = []
        edge_touches = 0
        for polygon in polygons:
            if len(polygon) < 6:
                continue
            polygon_np = np.array(polygon, dtype=np.int32).reshape(-1, 1, 2)
            area = cv2.contourArea(polygon_np)
            
            if area == 0:
                continue

            polygon_areas.append(area)

            M = cv2.moments(polygon_np)
            if M['m00'] == 0:
                self.logger.warning("Moment is 0. Skipping centroid calculation.")
                continue
            
            cX = M['m10'] / M['m00']
            cY = M['m01'] / M['m00']
            

            polygon_centroids.append((cX, cY))
            centre_dist = np.sqrt((cX - cx_img)**2 + (cY - cy_img)**2)
            centre_bias.append(centre_dist / max_dist)

            pts = polygon_np.reshape(-1, 2)

            if (
                (pts[:, 0] == 0).any() or
                (pts[:, 1] == 0).any() or
                (pts[:, 0] == w - 1).any() or
                (pts[:, 1] == h - 1).any()
            ):
                edge_touches += 1
        
        total_mask_area = sum(polygon_areas)
            
        return {
            "areas": polygon_areas,
            "centroids": polygon_centroids,
            "counts": len(polygon_areas),
            "total_areas": total_mask_area,
            "area_ratios": total_mask_area / image_area if image_area else 0,
            "centre_bias": centre_bias,
            "edge_touching": edge_touches
        }
    
    def _compute_heatmap(self, centroids):
        '''
        Computes a heatmap of the centroids.
        '''
        if not self.only_one_shape:
            self.logger.info("Cannot compute centroid heatmap: mask tiles have different shapes. Returning None for centroid_heatmap.")
            return None
        heatmap = np.zeros(self.ref_shape, dtype=np.float32)

        for sublist in centroids:
            for cX, cY in sublist:
                ix, iy = int(round(cX)), int(round(cY))
                if 0 <= iy < heatmap.shape[0] and 0 <= ix < heatmap.shape[1]:
                    heatmap[iy, ix] += 1
        return heatmap
    
    def compute_object_stats(self, filtered_masks=None):
        '''
        Computes and returns statistics about mask objects.

        Returns:
            dict with the following keys:
                'areas': list of lists, each sublist contains the areas of objects in an image/tile. Allows you to see how large each average object is. Contrast with 'total_areas'.
                'centroids': list of lists, each sublist contains (x, y) tuples for object centroids in an image/tile
                'counts': list of ints, number of objects per image/tile
                'total_areas': list of floats, total mask area per image/tile. Allows you to see how much of each image is covered by objects. Contrast with 'areas'.
                'area_ratios': list of floats, ratio of total mask area to image area per image/tile
                'centre_bias': list of lists, each sublist contains the normalized distance of each centroid from the image center
                'edge_touching': list of ints, number of objects touching the image edge per image/tile
                'centroid_heatmap': np.ndarray or None, heatmap of centroid locations if all shapes are the same, else None
                'image_shapes': list of tuples, each tuple contains the shape of the correspinding image/mask
        '''
        
        geometry_stats = {
            'areas'        : [],
            'centroids'    : [],
            'counts'       : [],
            'total_areas'  : [],
            'area_ratios'  : [],
            'centre_bias'  : [],
            'edge_touching': [], 
            'image_shapes': []
        }

        if filtered_masks is None:
            masks_iter = (self.load_mask(i) for i in self.sample_indices)
        else:
            masks_iter = iter(filtered_masks)

        for mask in masks_iter:
            polygons = self.annotation_generator.mask_to_polygons(mask)
            result = self._compute_single_mask_stats(mask, polygons)
            if result is None:
                continue
            
            geometry_stats["areas"].append(result["areas"])
            geometry_stats["centroids"].append(result["centroids"])
            geometry_stats["counts"].append(result["counts"])
            geometry_stats["total_areas"].append(result["total_areas"])
            geometry_stats["area_ratios"].append(result["area_ratios"])
            geometry_stats["centre_bias"].append(result["centre_bias"])
            geometry_stats["edge_touching"].append(result["edge_touching"])
            geometry_stats["image_shapes"].append(mask.shape[:2])
        
        geometry_stats["centroid_heatmap"] = self._compute_heatmap(geometry_stats["centroids"])
        
        return geometry_stats
    

    # --- Visualisation Methods --- #
    def plot_image_size_distribution(self):
        return self.plotter.plot_image_size_distribution(self.image_shapes_counts, self.mask_shapes_counts)
    
    def get_layer_source(self, spatial_metadata):
        return self.plotter.get_layer_source(spatial_metadata, self.spatial_mode)

    def calc_zoom_for_map(self, minx, miny, maxx, maxy):
        return self.plotter.calc_zoom_for_map(minx, miny, maxx, maxy)
    
    def get_bounds_area(self, minx, miny, maxx, maxy):
        return self.plotter.get_bounds_area(minx, miny, maxx, maxy)

    def _pad_bounds_to_aspect(self, minx, miny, maxx, maxy, target_aspect):
        return self.plotter.pad_bounds_to_aspect(minx, miny, maxx, maxy, target_aspect)

    def plot_spatial_metadata(self, final_gdf, center_lat, center_lon, zoom_level, bounds_area, bounds=None):
        return self.plotter.plot_spatial_metadata(final_gdf, center_lat, center_lon, zoom_level, bounds_area, bounds)
    
    def plot_country_distribution(self, spatial_metadata):
        return self.plotter.plot_country_distribution(spatial_metadata)

    def plot_colour_distribution_analysis(self, colour_data):
        return self.plotter.plot_colour_distribution_analysis(colour_data)

    def plot_channels_histogram(self, hist_data):
        return self.plotter.plot_channels_histogram(hist_data)

    def plot_average_image(self, avg_img):
        return self.plotter.plot_average_image(avg_img)

    def plot_intensity_heatmap(self, avg_img):
        return self.plotter.plot_intensity_heatmap(avg_img)
    
    def plot_vegetation_water_indices(self, vegetation_water_indices):
        return self.plotter.plot_vegetation_water_indices(vegetation_water_indices)

    def plot_contrast_heatmap(self, contrast_heatmap, window_size=25):
        return self.plotter.plot_contrast_heatmap(contrast_heatmap, window_size=window_size)

    def plot_object_count_distribution(self, counts, bins=30):
        return self.plotter.plot_object_count_distribution(counts, bins=bins)

    def plot_object_area_distribution(self, areas):
        return self.plotter.plot_object_area_distribution(areas)

    def plot_object_centroids(self, centroids, image_shape):
        return self.plotter.plot_object_centroids(centroids, image_shape)

    def plot_pixel_heatmap(self, heatmap, smooth=True, sigma=1.2):
        return self.plotter.plot_pixel_heatmap(heatmap, smooth=smooth, sigma=sigma)


    def plot_centre_bias_distribution(self, centre_bias):
        return self.plotter.plot_centre_bias_distribution(centre_bias)

    def plot_edge_touching_distribution(self, edge_touching):
        return self.plotter.plot_edge_touching_distribution(edge_touching)


    # --- Multiclass Dataset Object Helper --- #
    def object_statistics(self, filtered_masks=None):
        obj_stats = self.compute_object_stats(filtered_masks=filtered_masks)

        for k, v in obj_stats.items():
            if k != 'centroid_heatmap':
                print(f"{k}: {type(v)} (length: {len(v) if hasattr(v, '__len__') else 'n/a'})")
        
        self.plot_object_area_distribution(obj_stats.get('areas', []))
        self.plot_object_centroids(obj_stats.get('centroids', []), obj_stats.get('image_shapes', None))
        self.plot_object_count_distribution(obj_stats.get('counts', []))
        self.plot_centre_bias_distribution(obj_stats.get('centre_bias', []))
        self.plot_edge_touching_distribution(obj_stats.get('edge_touching', []))

        if obj_stats.get('centroid_heatmap', None) is not None:
            print("\n--- Centroid Heatmap ---")
            self.plot_pixel_heatmap(obj_stats['centroid_heatmap'])
    
    def _is_background_class(self, class_value) -> bool:
        return class_value == 0 or (
            isinstance(class_value, (tuple, list, np.ndarray)) and all(v == 0 for v in class_value)
        )

    def _get_foreground_classes(self, context: dict) -> list:
        if context["foreground_classes"] is None:
            context["foreground_classes"] = [c for c in self.classes if not self._is_background_class(c)]
        return context["foreground_classes"]

    def _get_cached_average_image(self, context: dict):
        if context["avg_img"] is None:
            context["avg_img"] = self.compute_average_image()
        return context["avg_img"]


    def _eligible_sample_indices_for_class(self, context: dict, class_id: int) -> list[int]:
        if not context.get("_eligible_warmed"):
            foreground_classes = self._get_foreground_classes(context)
            d = {c: [] for c in foreground_classes}
            for i in self.sample_indices:
                m = self.load_mask(i)
                if m is None:
                    continue
                p = set(np.unique(m).tolist())
                for c in foreground_classes:
                    if c in p:
                        d[c].append(i)
            context["eligible_sample_indices_by_class"] = d
            context["_eligible_warmed"] = True
        return list(context["eligible_sample_indices_by_class"].get(class_id, []))
            
            

    def _compute_multiclass_summary(self, context: dict):
        if context["multiclass_summary"] is not None:
            return context["multiclass_summary"]

        foreground_classes = self._get_foreground_classes(context)

        class_ids, image_counts, object_counts, total_areas, area_ratios = [], [], [], [], []

        for class_id in foreground_classes:
            if class_id not in context["obj_stats_by_class"]:
                eligible = self._eligible_sample_indices_for_class(context, class_id)
                filtered_masks = []
                for i in eligible:
                    mask = self.load_mask(i)
                    if mask is not None:
                        filtered_masks.append(self.image_processor.filter_mask_by_class_id(mask, class_id, self.set_name))
                context["obj_stats_by_class"][class_id] = self.compute_object_stats(filtered_masks=filtered_masks)

            s = context["obj_stats_by_class"][class_id]
            counts = np.asarray(s.get("counts", []), dtype=np.float64)
            totals = np.asarray(s.get("total_areas", []), dtype=np.float64)
            ratios = np.asarray(s.get("area_ratios", []), dtype=np.float64)

            class_ids.append(class_id)
            image_counts.append(int((counts > 0).sum()))
            object_counts.append(int(counts.sum()))
            total_areas.append(float(totals.sum()))
            area_ratios.append(float(ratios.mean()) if ratios.size else 0.0)

        context["multiclass_summary"] = (class_ids, image_counts, object_counts, total_areas, area_ratios)
        return context["multiclass_summary"]


    def plot_multiclass_object_summary(self, class_ids, image_counts, object_counts, total_areas, area_ratios):
        return self.plotter.plot_multiclass_object_summary(class_ids, image_counts, object_counts, total_areas, area_ratios)


    # --- Report Section Builders --- #
    def _build_section_file_types(self, idx: int, include_in_pdf: bool = True, include_images: bool = True, include_text: bool = True, show_inline_override: bool | None = None) -> ReportSection:
        '''Builds a report section for the file types in the dataset folder.'''
        file_types = self.file_handler.get_file_types_in_dataset(os.path.dirname(self.image_paths[0]) if self.image_paths else '.')
        text_lines = [f"Extension: '{ext or '[no extension]'}' | Count: {len(examples)} | Examples: {examples}" for ext, examples in file_types.items()]
        text_lines.append(f"Total unique file types: {len(file_types)}\n")
        sec = ReportSection(
            idx=idx, 
            slug='file_types', 
            title='File Types in Dataset Folder', 
            text_lines=text_lines,
            include_in_pdf=include_in_pdf, 
            include_images=include_images, 
            include_text=include_text, 
            show_inline_override=show_inline_override)
        return sec

    
    def _build_section_unique_values(self, idx: int, include_in_pdf: bool = True, include_images: bool = True, include_text: bool = True, show_inline_override: bool | None = None) -> ReportSection:
        '''Builds a report section for the unique values in the sampled mask images.'''
        unique_values = self.all_unique_mask_values()
        text_lines = [f"Total number of unique values: {len(unique_values)}"]
        text_lines.append(f"Unique values: {unique_values}")
        text_lines.append(f"This is a {'single class' if self.only_one_class else 'multiclass'} dataset.")

        sec = ReportSection(
            idx=idx, 
            slug='unique_mask_values', 
            title='Unique Values in Sampled Mask Images', 
            text_lines=text_lines,
            include_in_pdf=include_in_pdf, 
            include_images=include_images, 
            include_text=include_text, 
            show_inline_override=show_inline_override)
        return sec

    def _build_section_random_grid(self, idx: int, include_in_pdf: bool = True, include_images: bool = True, include_text: bool = True, show_inline_override: bool | None = None) -> ReportSection:
        '''Builds a report section for the random grid of image-mask pairs.'''
        fig = self.visualiser.display_random_grid(self.image_paths, self.mask_paths, n=10)
        sec = ReportSection(
            idx=idx, 
            slug='random_grid', 
            title='Random Grid of Image-Mask Pairs', 
            figures=[fig] if fig is not None else [],
            include_in_pdf=include_in_pdf, 
            include_images=include_images, 
            include_text=include_text, 
            show_inline_override=show_inline_override)
        return sec
    
    def _build_section_spatial_metadata(self, context: dict, idx: int, include_in_pdf: bool = True, include_images: bool = True, include_text: bool = True, show_inline_override: bool | None = None) -> ReportSection:
        '''Builds a report section for the spatial metadata.'''

        if context['spatial_metadata'] is None:
            context['spatial_metadata'] = self.compute_spatial_metadata()

        country_dist_fig = self.plot_country_distribution(context['spatial_metadata'])

        if context['spatial_layer'] is None:
            context['spatial_layer'] = self.get_layer_source(context['spatial_metadata'])
        
        figures = []
        text_lines = []

        mpl_fig = None 

        if context['spatial_layer'] is not None:
            _, center_lat, center_lon, minx, miny, maxx, maxy = context["spatial_layer"]
            if context["zoom_level"] is None:
                context["zoom_level"] = self.calc_zoom_for_map(minx, miny, maxx, maxy)
            if context["bounds_area"] is None:
                context["bounds_area"] = self.get_bounds_area(minx, miny, maxx, maxy)

            if context["bounds_area"] is None:
                self.logger.warning("Bounds area is None; skipping map plot.")
            elif context["bounds_area"] > self.config.get('max_bounds_area', 500_000):
                self.logger.warning("Union extent exceeds max bounds area; skipping map plot.")
            else:
                a4_aspect = WriteReport.A4_LANDSCAPE_SIZE[0] / WriteReport.A4_LANDSCAPE_SIZE[1]
                padded_bounds = self._pad_bounds_to_aspect(minx, miny, maxx, maxy, a4_aspect)
                go_fig = self.plot_spatial_metadata(context['spatial_layer'][0], context['spatial_layer'][1], context['spatial_layer'][2], context['zoom_level'], context['bounds_area'], padded_bounds)
                if go_fig is not None:
                    try:
                        img_bytes = go_fig.to_image(format="png", scale=1)
                        pil_img = Image.open(io.BytesIO(img_bytes)).convert("RGB")
                        mpl_fig, ax = plt.subplots(
                            figsize=(WriteReport.A4_LANDSCAPE_SIZE)
                        )
                        ax.imshow(pil_img)
                        ax.axis("off")
                        mpl_fig.tight_layout(pad=0)
                    except Exception:
                        self.logger.exception("Failed to rasterise spatial metadata map to Matplotlib figure")
                else:
                    text_lines.append("Failed to plot spatial metadata map.")
        else:
            text_lines.append("Spatial metadata map: unavailable (no valid CRS/bounds for any record).")


        if include_text:
            if context["spatial_layer"] is not None and mpl_fig is not None:
                _, center_lat, center_lon, minx, miny, maxx, maxy = context["spatial_layer"]
                text_lines.extend(self._summarise_spatial_metadata(
                    spatial_metadata=context["spatial_metadata"],
                    center_lat=center_lat,
                    center_lon=center_lon,
                    minx=minx,
                    miny=miny,
                    maxx=maxx,
                    maxy=maxy,
                    zoom_level=context["zoom_level"],
                ))
            else:
                text_lines.extend(self._summarise_spatial_metadata_no_map(context["spatial_metadata"]))
        
        if self.spatial_mode == "dataset_level":
            text_lines.append("Spatial metadata provenance: dataset-level user input (coarse).")
        
        if mpl_fig is not None:
            figures.append(mpl_fig)
        if country_dist_fig is not None:
            figures.append(country_dist_fig)


        sec = ReportSection(
            idx=idx, 
            slug='spatial_metadata', 
            title='Spatial Metadata', 
            text_lines=text_lines,
            figures=figures,
            include_in_pdf=include_in_pdf, 
            include_images=include_images, 
            include_text=include_text, 
            show_inline_override=show_inline_override)
        return sec
    
    def _build_section_basic_metrics(self, idx: int, include_in_pdf: bool = True, include_images: bool = True, include_text: bool = True, show_inline_override: bool | None = None) -> ReportSection:
        '''Builds a report section for the basic metrics.'''
        metrics = self.compute_basic_metrics()
        text_lines = self._summarise_basic_metrics(metrics)
    
        sec = ReportSection(
            idx=idx, 
            slug='basic_metrics', 
            title='Basic Metrics', 
            text_lines=text_lines,
            include_in_pdf=include_in_pdf, 
            include_images=include_images, 
            include_text=include_text, 
            show_inline_override=show_inline_override)
        return sec
    
    def _build_section_image_size_distribution(self, idx: int, include_in_pdf: bool = True, include_images: bool = True, include_text: bool = True, show_inline_override: bool | None = None) -> ReportSection:
        '''Builds a report section for the image size distribution.'''
        fig = self.plot_image_size_distribution()
        sec = ReportSection(
            idx=idx, 
            slug='image_size_distribution', 
            title='Image Size Distribution', 
            figures=[fig],
            include_in_pdf=include_in_pdf, 
            include_images=include_images, 
            include_text=include_text, 
            show_inline_override=show_inline_override)
        return sec
    
    def _build_section_colour_distribution_analysis(self, idx: int, include_in_pdf: bool = True, include_images: bool = True, include_text: bool = True, show_inline_override: bool | None = None) -> ReportSection:
        '''Builds a report section for the colour distribution analysis.'''
        colour_dist = self.compute_colour_distribution()
        figs = self.plot_colour_distribution_analysis(colour_dist)
        figures = figs if figs else []
        text_lines = [f"\n -Total Unique Colours: {colour_dist.get('total_unique_colours', 'N/A')}"]
        text_lines.append(f"\n -Total Pixels Analysed: {colour_dist.get('total_pixels_analysed', 'N/A')}")
        text_lines.append(f"\n -Dominant Colour (BGR): {colour_dist.get('dominant_colour', 'N/A')}")
        text_lines.append(f"\n -Average Colour (BGR): {colour_dist.get('average_colour_bgr', 'N/A')}")
 
        sec = ReportSection(
            idx=idx, 
            slug='colour_distribution_analysis', 
            title='Colour Distribution Analysis',
            text_lines=text_lines,
            figures=figures,
            include_in_pdf=include_in_pdf, 
            include_images=include_images, 
            include_text=include_text, 
            show_inline_override=show_inline_override)
        return sec
    
    def _build_section_intensity_analysis(self, idx: int, include_in_pdf: bool = True, include_images: bool = True, include_text: bool = True, show_inline_override: bool | None = None) -> ReportSection:
        '''Builds a report section for the intensity analysis.'''
        intensity_hist = self.compute_intensity_histogram()

        text_lines = []
        text_lines.append(f"\n - Overall Mean Intensity: {intensity_hist.get('mean_intensity', 'N/A'):.2f}")
        text_lines.append(f"\n - Overall Std Intensity: {intensity_hist.get('std_intensity', 'N/A'):.2f}")
        text_lines.append(f"\n - Overall Min Intensity: {intensity_hist.get('min_intensity', 'N/A')}")
        text_lines.append(f"\n - Overall Max Intensity: {intensity_hist.get('max_intensity', 'N/A')}")
        if 'percentiles' in intensity_hist:
            percentiles = intensity_hist['percentiles']
            text_lines.append(f"\n Percentiles [1%, 25%, 50%, 75%, 99%]: {[f'{p:.2f}' for p in percentiles]}")
        for colour in ['B', 'G', 'R']:
            if f'{colour}_mean_intensity' in intensity_hist:
                text_lines.append(f"\n {colour} Channel Statistics:")
                text_lines.append(f"\n -  Mean: {intensity_hist[f'{colour}_mean_intensity']:.2f}")
                text_lines.append(f"\n -  Std: {intensity_hist[f'{colour}_std_intensity']:.2f}")
                text_lines.append(f"\n -  Min: {intensity_hist[f'{colour}_min_intensity']}")
                text_lines.append(f"\n -  Max: {intensity_hist[f'{colour}_max_intensity']}")
                percentiles = intensity_hist[f'{colour}_percentiles']
                text_lines.append(f"\n Percentiles [1%, 25%, 50%, 75%, 99%]: {[f'{p:.2f}' for p in percentiles]}")
        fig = self.plot_channels_histogram(intensity_hist)
        sec = ReportSection(
            idx=idx, 
            slug='intensity_analysis', 
            title='Intensity Analysis', 
            text_lines=text_lines,
            figures=[fig],
            include_in_pdf=include_in_pdf, 
            include_images=include_images, 
            include_text=include_text, 
            show_inline_override=show_inline_override)
        return sec 

    def _build_section_average_image(self, context: dict, idx: int, include_in_pdf: bool = True, include_images: bool = True, include_text: bool = True, show_inline_override: bool | None = None) -> ReportSection:
        '''Builds a report section for the average image.'''
        avg_img = self._get_cached_average_image(context)
        fig = self.plot_average_image(avg_img)
        sec = ReportSection(
            idx=idx, 
            slug='average_image', 
            title='Average Image', 
            figures=[fig],
            include_in_pdf=include_in_pdf, 
            include_images=include_images, 
            include_text=include_text, 
            show_inline_override=show_inline_override)
        return sec

    def _build_section_intensity_heatmap(self, context: dict, idx: int, include_in_pdf: bool = True, include_images: bool = True, include_text: bool = True, show_inline_override: bool | None = None) -> ReportSection:
        '''Builds a report section for the intensity heatmap.'''
        avg_img = self._get_cached_average_image(context)
        fig = self.plot_intensity_heatmap(avg_img)
        sec = ReportSection(
            idx=idx, 
            slug='intensity_heatmap', 
            title='Intensity Heatmap', 
            figures=[fig],
            include_in_pdf=include_in_pdf, 
            include_images=include_images, 
            include_text=include_text, 
            show_inline_override=show_inline_override)
        return sec

    def _build_section_contrast_heatmap(self, context: dict, idx: int, include_in_pdf: bool = True, include_images: bool = True, include_text: bool = True, show_inline_override: bool | None = None) -> ReportSection:
        '''Builds a report section for the contrast heatmap.'''
        avg_img = self._get_cached_average_image(context)
        contrast_heatmap = self.compute_contrast_heatmap(avg_img)
        fig = self.plot_contrast_heatmap(contrast_heatmap)
        sec = ReportSection(
            idx=idx, 
            slug='contrast_heatmap', 
            title='Contrast Heatmap', 
            figures=[fig],
            include_in_pdf=include_in_pdf, 
            include_images=include_images, 
            include_text=include_text, 
            show_inline_override=show_inline_override)
        return sec

    def _build_section_vegetation_water_indices(self, context: dict, idx: int, include_in_pdf: bool = True, include_images: bool = True, include_text: bool = True, show_inline_override: bool | None = None) -> ReportSection:
        """Build section for all image indices visualisation/summary statistics."""
        vegetation_water_indices = self.compute_indices()
        figures = self.plot_vegetation_water_indices(vegetation_water_indices)

        sec = ReportSection(
            idx=idx,
            slug='vegetation_water_indices',
            title='Vegetation/Water Indices',
            figures=figures,
            include_in_pdf=include_in_pdf,
            include_images=include_images,
            include_text=include_text,
            show_inline_override=show_inline_override)
        return sec

    def _build_section_object_statistics_per_class(self, context: dict, idx: int, class_id: int, include_in_pdf: bool = True, include_images: bool = True, include_text: bool = True, show_inline_override: bool | None = None) -> ReportSection:

        eligible = self._eligible_sample_indices_for_class(context, class_id)
        obj_stats = context["obj_stats_by_class"].get(class_id, None)
        if obj_stats is None:
            filtered_for_stats = []
            for i in eligible:
                mask = self.load_mask(i)
                if mask is not None:
                    filtered_for_stats.append(self.image_processor.filter_mask_by_class_id(mask, class_id, self.set_name))
            obj_stats = self.compute_object_stats(filtered_masks=filtered_for_stats)
            context["obj_stats_by_class"][class_id] = obj_stats

        if not eligible:
            random_idx = np.random.choice(self.sample_indices)
        else:
            random_idx = np.random.choice(eligible)
        
        raw_mask = self.load_mask(random_idx)
        filtered_mask = self.image_processor.filter_mask_by_class_id(raw_mask, class_id, self.set_name)

        figures = []
        for fig in [
            self.plot_object_area_distribution(obj_stats.get("areas", [])),
            self.plot_object_centroids(obj_stats.get("centroids", []), obj_stats.get("image_shapes", None)),
            self.plot_object_count_distribution(obj_stats.get("counts", [])),
            self.plot_centre_bias_distribution(obj_stats.get("centre_bias", [])),
            self.plot_edge_touching_distribution(obj_stats.get("edge_touching", [])),
            self.plot_pixel_heatmap(obj_stats.get("centroid_heatmap")),
            self.visualiser.return_image_mask_pair(self.load_image(random_idx), filtered_mask),
            ]:
            if fig is not None:
                figures.append(fig)
        
        counts = np.asarray(obj_stats.get("counts", []), dtype=np.int64)
        area_ratios = np.asarray(obj_stats.get("area_ratios", []), dtype=np.float64)
        metrics = {
            "class_id": class_id,
            "num_images_analysed": int(len(counts)),
            "images_with_objects": int((counts > 0).sum()) if counts.size else 0,
            "total_objects": int(counts.sum()) if counts.size else 0,
            "mean_objects_per_image": float(counts.mean()) if counts.size else 0.0,
            "mean_area_ratio": float(area_ratios.mean()) if area_ratios.size else 0.0,
        }

        sec = ReportSection(
            idx=idx,
            slug=f"object_statistics_{class_id}",
            title=f"Object Statistics for Class {class_id}",
            metrics=metrics,
            figures=figures,
            include_in_pdf=include_in_pdf,
            include_images=include_images,
            include_text=include_text,
            show_inline_override=show_inline_override
        )
        return sec

    def _build_section_multiclass_object_summary(self, context: dict, idx: int, include_in_pdf: bool = True, include_images: bool = True, include_text: bool = True, show_inline_override: bool | None = None) -> ReportSection:
        '''Builds a section for the multiclass object summary.'''

        class_ids, image_counts, object_counts, total_areas, area_ratios = self._compute_multiclass_summary(context)
        fig = self.plot_multiclass_object_summary(class_ids, image_counts, object_counts, total_areas, area_ratios)
        sec = ReportSection(
            idx=idx,
            slug="multiclass_object_summary",
            title="Multiclass Object Summary",
            figures=[fig],
            include_in_pdf=include_in_pdf,
            include_images=include_images,
            include_text=include_text,
            show_inline_override=show_inline_override
        )
        return sec
    
    def _build_section_triplet_check(self, context: dict, idx: int, include_in_pdf: bool = True, include_images: bool = True, include_text: bool = True, show_inline_override: bool | None = None) -> ReportSection:
        '''Assuming that this is a POST-PROCESSING report, this section will check a few random triplets of image, mask, and label.'''
        if self.stage == 'post':
            text_lines = []
            text_lines.append("This section checks a few random triplets of image, mask, and label.")
            
            images_dir = os.path.join(self.data_dir, "images")
            image_files = [f for f in os.listdir(images_dir) if f.lower().endswith(".jpg")]
            k = min(3, len(image_files))
            if k == 0:
                figures = []
                text_lines.append("No images found in the class directory.")
            else:
                selected = np.random.choice(image_files, size=k, replace=False)  
                pairs = [self.visualiser.check_random_triplet(self.data_dir, image_file=f, show_inline=False) for f in selected]
                figures = [fig for fig, _ in pairs if fig is not None]
                for _, lines in pairs:
                    text_lines.extend(lines)
        else:
            figures = []
            text_lines = ['This section is only available for POST-PROCESSING reports.']
        
        sec = ReportSection(
            idx=idx,
            slug="triplet_check",
            title="Triplet Check",
            text_lines=text_lines,
            figures=figures,
            include_in_pdf=include_in_pdf,
            include_images=include_images,
            include_text=include_text,
            show_inline_override=show_inline_override
        )
        return sec

    # --- Report --- #
    def build_sections(self, context: dict | None = None) -> list[ReportSection]:
        """Build all report sections in deterministic order."""
        context = context or EDAContext().as_dict()
        return self.sections_builder.build_sections(context)

    def report(
        self, 
        show_inline: bool = False,
        save_pdf: bool = True,
        save_images: bool = True,
        save_summary: bool = True,
        output_dir: str | None = None):
        '''
        Runs a full EDA report: computes metrics, saves summaries, and shows key plots. Produces a PDF report and a summary JSON file.
        While it is possible to both show the report inline AND save the PDF, it is not recommended to do both. 
        Args:
            stage (str): 'pre' for pre-processing, 'post' for post-processing. Used for labeling/reporting.
            show_inline (bool): Whether to show plots inline.
            save_pdf (bool): Whether to save the PDF report.
            save_images (bool): Whether to save the images.
            save_summary (bool): Whether to save the summary JSON file.
            output_dir (str): The directory to save the report and artefacts.
        '''
        stage = self.stage
        base_dir = output_dir or "reports"
        artefacts = ReportArtefactManager(base_dir=base_dir, stage=stage, set_name=self.set_name)
        writer = WriteReport(artefacts=artefacts, set_name=self.set_name)
        context = EDAContext().as_dict()
        sections: list[ReportSection] = []

        if show_inline:
            print(f"\n{'='*40}\nDATASET EDA REPORT ({'PRE' if stage=='pre' else 'POST'}-PROCESSING)\n{'='*40}")


        sections = self.build_sections(context=context)

        # save report
        writer.render_report(sections, show_inline=show_inline, save_pdf=save_pdf, save_images=save_images, save_summary=save_summary)

        if show_inline:
            print(f"\n{'='*40}\nEND OF REPORT\n{'='*40}")
        any_save = save_pdf or save_images or save_summary
        return {
             "stage": stage,
             "run_dir": str(artefacts.run_dir) if any_save else None,
             "pdf_path": str(artefacts.pdf_path) if save_pdf else None,
             "summary_path": str(artefacts.summary_path) if save_summary else None,
             "num_sections": len(sections)
            }